version: '3.8'

services:
  # 1. DATABASE (PostgreSQL)
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qr_platform
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data  # <--- MUST LOOK LIKE THIS
    ports:
      - "5432:5432"

  # 2. CACHE & QUEUE (Redis)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 3. API GATEWAY (Backend)
  # ... inside services: ...
  api:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:     # <--- ADD THIS SECTION
      - .env      # <--- This tells Docker to read your .env file
    depends_on:
      - db
      - redis
  # ... existing services ...
  worker:
    build: ./analytics-worker
    depends_on:
      - db
      - redis
    env_file:
      - .env
  
  # 4. DASHBOARD (Frontend)
  dashboard:
    build: ./dashboard
    ports:
      - "8080:3000" # We map port 8080 on your laptop to 3000 inside the container
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - api